[package]
name = "diesel-views"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.4", features = [
    "postgres",
    "i-implement-a-third-party-backend-and-opt-into-breaking-changes", # For BoxedSelectStatement
] }
